# Generated by Django 5.1 on 2024-08-23 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('orden', models.PositiveIntegerField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('workflow', models.CharField(blank=True, max_length=255, null=True)),
                ('macro_path', models.CharField(blank=True, max_length=255, null=True)),
                ('source_path', models.CharField(blank=True, max_length=255, null=True)),
                ('destination_path', models.CharField(blank=True, max_length=255, null=True)),
                ('email_recipients', models.TextField(blank=True, null=True)),
                ('email_message', models.TextField(blank=True, null=True)),
                ('secuencial', models.BooleanField(default=True)),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informes.proceso')),
            ],
        ),
    ]
