# Generated by Django 5.1 on 2024-08-25 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informe',
            old_name='secuencial',
            new_name='is_sequential',
        ),
        migrations.RenameField(
            model_name='informe',
            old_name='macro_path',
            new_name='macro',
        ),
    ]
